---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: example
  state_top:
    base:
      "*":
        - example

platforms:
  - name: bento/debian-8.8

suites:
  - name: default
  
  - name: custom
    provisioner:
      pillars-from-files:
        example.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - example
